export const CONFIG = {

    STRIKE_VELOCITY_THRESHOLD: -0.018,
    STRIKE_ACCELERATION_THRESHOLD: -0.01,

    SMOOTHING_SLOW: 0.12,
    SMOOTHING_FAST: 0.45,

    PRESS_DEPTH: 0.62,
    RELEASE_DEPTH: 0.48,

    NOTE_COOLDOWN: 60,

    DEBUG: true
}